# Generated by Django 4.1.7 on 2023-04-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0003_usuario_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
